services:
  db:
    image: postgres:15
    container_name: typst-db
    environment:
      POSTGRES_USER: typst_user
      POSTGRES_PASSWORD: qaywsxedc
      POSTGRES_DB: typst_db
    ports:
      - "5433:5432"
    networks:
      - typst-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U typst_user -d typst_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    container_name: typst-api
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - typst-network
    command: sh -c "npm install && npm run dev"

  app:
    build: ./app
    container_name: typst-app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - typst-network
    environment:
      - DATABASE_URL=postgresql://typst_user:qaywsxedc@db:5432/typst_db
      - NEXT_PUBLIC_COMPILER_URL=http://127.0.0.1:3001
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: sh -c "bun install && bun x auth secret && bun x prisma generate && bun x prisma migrate deploy && bun dev"

  test:
    image: cypress/included:13.15.0
    container_name: typst_test
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./:/opt/app
    working_dir: /opt/app
    networks:
      - typst-network
    environment:
      - CYPRESS_baseUrl=http://app:3000

networks:
  typst-network:
    driver: bridge