name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start Docker Compose
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "Token present? ${GITHUB_TOKEN:0:8}****"
          docker compose up -d --build
          docker compose ps
          sleep 15

      - name: Run Cypress tests
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: docker compose run --rm test

      - name: Tear down Docker Compose
        if: always()
        run: docker compose down
